### ISSUE TITLE
Only images are deleted from cloudinary

### ISSUE THREAD

**Issue by BayBreezy** [finkinfridom/payload-cloudinary-plugin#13]
Hey @finkinfridom , me again lol

When I delete images from the admin ui, they get deleted in cloudinary but other file types are not.
e.g: I upload a csv/pdf/exe file - I see them in cloudinary even after they are deleted from the database.

I think it has to do with how the public ID's are stored for other files vs images. The public ID's for files other than images have the extension on them. So a csv file's public ID would look like this `[FOLDER_NAME]/jhgcv23lkjhbvkk.csv` while the image would be named  - `[FOLDER_NAME]/kjhv23glhkjlkblkjhb`

**Comment by finkinfridom** [comment]
Hey, I'll check the code and let you know.
Thanks for reporting

**Comment by finkinfridom** [comment]
Just published package version: 0.0.9 and tested it locally.
Please let me know

**Comment by BayBreezy** [comment]
@finkinfridom , Thanks again. 

Confirming that this is working 👍🏽
