### ISSUE TITLE
How to use this in collection? Please give an example | Please Update Readme

### ISSUE THREAD

**Issue by SanchitB23** [finkinfridom/payload-cloudinary-plugin#133]
I have done the configuration part as mentioned in the plugin readme, but still unable to successfully fulfil the request, when trying to upload getting error : ` ERROR (payload): APIError: Cloudinary: {}`

my `Server.ts` file

`  app.use(mediaManagement(cloudinaryConfig))`

My `cloudinaryConfig` Object

`const cloudinaryConfig = cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});`

My `payload.config.ts` file

`  plugins: [cloudinaryPlugin()],`

**Comment by finkinfridom** [comment]
hey @SanchitB23 when do you encounter the `API Error` issue?
which version of the plugin and `payload` are you using?

**Comment by finkinfridom** [comment]
hey @SanchitB23, are the `env` variables properly set?
There was an issue with the latest updates from `payload` (you can see here: https://github.com/finkinfridom/payload-cloudinary-plugin/issues/130) and maybe you're facing the same.
