### ISSUE TITLE
Can't find where to hide default input fields

### ISSUE THREAD

**Issue by joelapablaza** [finkinfridom/payload-cloudinary-plugin#198]
![Screenshot 2024-03-29 185330](https://github.com/finkinfridom/payload-cloudinary-plugin/assets/94097612/33571072-7f8d-4cb8-8a4d-c5aee4dec33c)

The uploading is working perfectly! But I just want to know if there is a way to hide those input files from the dashboard

**Comment by finkinfridom** [comment]
hey @joelapablaza those fields (at the moment) could not be marked as hidden.
Could I ask you the reason for hiding them?
Given that Cloudinary is a 3rd party tool, I strongly suggest to keep those fields (as they're read-only) to provide you meaningful information when debugging/troubleshooting issues.
