### ISSUE TITLE
Error: Types of parameters 'config' and 'config' are incompatible.

### ISSUE THREAD

**Issue by shubhamwebdesign** [finkinfridom/payload-cloudinary-plugin#29]
Type 'import("c:/WebDevelopment/MyProjects/Projects/portfolio/portfolio_backend/node_modules/payload-cloudinary-plugin/node_modules/payload/dist/config/types").Plugin' is not assignable to type 'import("c:/WebDevelopment/MyProjects/Projects/portfolio/portfolio_backend/node_modules/payload/dist/config/types").Plugin'.
  Types of parameters 'config' and 'config' are incompatible.

Got this warning after installing the package, its working in development but failing in production environemnt, how can i resolve this?

**Comment by finkinfridom** [comment]
I'll have a look at the issue and let you know

**Comment by finkinfridom** [comment]
hey @shubhamwebdesign which version are you using? the latest published?

**Comment by shubhamwebdesign** [comment]
Repo URL
https://github.com/shubhamwebdesign/portfolio_backend
payload version: "^1.0.9"
 payload-cloudinary-plugin version: "^0.0.11"

**Comment by finkinfridom** [comment]
Did you try to upgrade `payload` to version `1.2.x`?
Do you get the error at compilation time or runtime?

**Comment by shubhamwebdesign** [comment]
I won't be able to upgrade the payload version as only version 1.0.9 is compatible with payload-plugin-seo

**Comment by shubhamwebdesign** [comment]
After deleting and re-installing the node_modules the error is gone
